version: "3.8"

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=predictdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - mynetwork
    restart: always

  backend:
    image: backend:latest
    ports:
      - "9000:9000"
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=predictdb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_PORT=3306
    networks:
      - mynetwork
    depends_on:
      - mysql
    restart: always

networks:
  mynetwork:
    name: deploy-link
    external: true
